### ISSUE TITLE
main program

### ISSUE THREAD

**Issue by cgf21st** [muhanzhang/SEAL#11]
Hello, run the main program to ask the following questions:
'rm' 不是内部或外部命令，也不是可运行的程序 
或批处理文件。 
Saving split-1 of 3...
错误使用 SEAL (line 90)
由于 'tempdata\USAir_1' 不存在，无法创建 'split_1.mat'。

出错 Main (line 83)
    parfor (ith_experiment = 1:numOfExperiment, workers)

how to solve it, thank you

**Comment by muhanzhang** [comment]
The code is tested on Linux. 'rm' is the removing command in Linux. If you use Windows, you may need to change these commands to Windows commands.

**Comment by cgf21st** [comment]
Thank you for your reply! I want to quote your article and compare it with your method. What command can ‘rm' be used in window instead? I tried it or not. look forward to your reply

**Comment by muhanzhang** [comment]
Hi, _del_ is the Windows equivalent of _rm_. But since you run on Windows, perhaps using the Python version is a better choice
