### ISSUE TITLE
编码

### ISSUE THREAD

**Issue by Volcano-plus** [muhanzhang/SEAL#13]
loss: 0.27501 acc: 0.87500: 100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚
鈻堚枅鈻堚枅鈻堚枅| 9/9 [00:00<00:00, 12.10batch/s]

请问我应该在哪里修改？

**Comment by muhanzhang** [comment]
Hi, I see a lot of unreadable code. Is your question about why such unreadable code is generated? If so, can you try to enable utf-8 coding in your Python IDE or so? Your issue seems to be because the progress bar from tqdm gets to be shown improperly.

**Comment by Volcano-plus** [comment]
谢谢！
