### ISSUE TITLE
from mian import *

### ISSUE THREAD

**Issue by try-to-anything** [muhanzhang/SEAL#14]
hello , main  package in Ubuntu environment, download is unsuccessful。

Running setup.py install for main ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fJikpq/main/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pB5uyz-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-2.7
    error: file '/tmp/pip-build-fJikpq/main/main' does not exist

**Comment by muhanzhang** [comment]
Hi, this repo doesn't have a setup.py. Which command were you running?

**Comment by try-to-anything** [comment]
thank you , I have run successfully.
