### ISSUE TITLE
关于node2vec的设

### ISSUE THREAD

**Issue by Volcano-plus** [muhanzhang/SEAL#15]
请问，对比实验中，node2vec是用到了那种edge feature?原文中有四种方式，但是原文中在link prediction实验中参数也没有说清楚。请问你用的哪种方式？参数又是如何设置的？还请赐教。

**Comment by muhanzhang** [comment]
Hi, as suggested by the experimental results of node2vec paper, I chose Hadamard product of node features as link feature. For more details about this baseline, please refer to "embedding_lp.m" file in the Matlab version of SEAL. The Matlab version was used to generate the experimental results.

**Comment by Volcano-plus** [comment]
Thank you. 
I found AUC of node2vec in original is 0.9680(facebook), while in your Table 12 is 0.9905. As far as I know, the parameters are the same, so I would like to know the reason.

**Comment by muhanzhang** [comment]
I don't know the exact reasons. One possible reason is the difference in how they sample negative testing links. But since they do not provide the evaluation code, I am not sure about it.
