### ISSUE TITLE
WCN, WAA

### ISSUE THREAD

**Issue by bjsrpt** [muhanzhang/SEAL#16]
Hi, I found weighted WCN and WAA in your project, but I'm confusing about how 'alpha' parameter is assigned?  Depends on cases? Can you please tell me anything I could do if I want to experiment on WCN and WAA? Thanks a lot

**Comment by muhanzhang** [comment]
Hi, sorry for the confusion. The WCA and WAA code are deprecated. I should have deleted them. They are something I came up with long time ago that I even forgot what their meanings are.
