### ISSUE TITLE
OSError: dlopen(.../pytorch_DGCNN/lib/build/dll/libgnn.so, 6): no suitable image found.

### ISSUE THREAD

**Issue by MengyangSun93** [muhanzhang/SEAL#17]
Hi, when I try to run, I receive the OSError: 

`OSError: dlopen(.../pytorch_DGCNN/lib/build/dll/libgnn.so, 6): no suitable image found.`

I've found online and can not solve this problem(even I use virtualenv), do you know what's wrong with it?

Actually, whatever python3 or python2.7 I use, as long as I run:

```
import ctypes
ctypes.CDLL(".../pytorch_DGCNN/lib/build/dll/libgnn.so")
```

I've got OSError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(.../pytorch_DGCNN/lib/build/dll/libgnn.so, 6): no suitable image found.  Did find:
	.../pytorch_DGCNN/lib/build/dll/libgnn.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	.../pytorch_DGCNN/lib/build/dll/libgnn.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by muhanzhang** [comment]
Hi, it seems to be a mac-os related error. Can you try to rebuild the C++ backend by typing "make clean" and "make -j4" under "pytorch_DGCNN/lib/"?

**Comment by MengyangSun93** [comment]
> Hi, it seems to be a mac-os related error. Can you try to rebuild the C++ backend by typing "make clean" and "make -j4" under "pytorch_DGCNN/lib/"?

Thank you ~

**Comment by mgao97** [comment]
Hi～
I have also encountered the above error.  The above method doesn't work for me.
Have you solved it? @MengyangSun93 
And Would you please offer other advice? @muhanzhang  Thanks a lot!

**Comment by changbenjamin** [comment]
These are the steps that helped me to rebuild the C++ backend for PyTorch DGCNN:

Open a terminal window and navigate to the 'pytorch_DGCNN/lib/' directory. You can use the following command to navigate to the directory:

**cd <path/to/pytorch_DGCNN/lib>**

Run the 'make clean' command to clean the previously built object files and libraries. This command removes any previously built files, so make sure you have saved any changes you have made to the source code. For example:

**make clean**

Run the 'make -j4' command to rebuild the C++ backend with 4 threads. This command compiles the source code and creates a new library file. The '-j' option specifies the number of threads to use for compilation, which can speed up the compilation process on multi-core processors. For example:

**make -j4**

Once the compilation is finished, you should see a new libgnn.so file in the pytorch_DGCNN/lib/build/dll/ directory. You can try running your Python script again to see if the issue has been resolved.

ChatGPT helped me understand @muhanzhang's advice!
