### ISSUE TITLE
NameError: name 'cmd_args' is not defined

### ISSUE THREAD

**Issue by cgf21st** [muhanzhang/SEAL#22]
张博士，您好！使用python3.5执行SEAL遇到错误，NameError: name 'cmd_args' is not defined，不知如何解决！谢谢！

**Comment by muhanzhang** [comment]
Hi，请问是否有download pytorch_DGCNN 到 SEAL 的同级目录？cmd_args来自pytorch_DGCNN

**Comment by xihairanfeng** [comment]
> Hi，请问是否有download pytorch_DGCNN 到 SEAL 的同级目录？cmd_args来自pytorch_DGCNN

您好，我也是遇到了一样的问题。已经下载好了pytorch_DGCNN在SEAL的同级的目录，但是我实在SEAL下面的python文件夹中执行的python Main.py --data-name USAir

**Comment by muhanzhang** [comment]
Hi，你可以试试直接在Linux里面重装SEAL。你在#20里的情况可能说明了你先download到windows再上传到Linux导致了一些换行符不兼容。

**Comment by xihairanfeng** [comment]
> Hi，你可以试试直接在Linux里面重装SEAL。你在#20里的情况可能说明了你先download到windows再上传到Linux导致了一些换行符不兼容。

好的，非常感谢您的回复，我确实在windows下载好的代码，之后上传到服务器的，然后在服务器中进行的。我会尝试您的意见的

**Comment by xihairanfeng** [comment]
> > Hi，你可以试试直接在Linux里面重装SEAL。你在#20里的情况可能说明了你先download到windows再上传到Linux导致了一些换行符不兼容。
> 
> 好的，非常感谢您的回复，我确实在windows下载好的代码，之后上传到服务器的，然后在服务器中进行的。我会尝试您的意见的

average training of epoch 48: loss 0.24618 acc 0.89971 auc 0.96343
loss: 0.48293 acc: 0.81250: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 72.46batch/s]
average validation of epoch 48: loss 0.35915 acc 0.85079 auc 0.92585
loss: 0.23922 acc: 0.94000: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [00:01<00:00, 45.09batch/s]
average training of epoch 49: loss 0.24455 acc 0.89882 auc 0.96386
loss: 0.45177 acc: 0.84375: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 71.77batch/s]
average validation of epoch 49: loss 0.35400 acc 0.85864 auc 0.92675
Final test performance: epoch 43: loss 0.28225 acc 0.88208 auc 0.95344
我重新直接在服务器上进行了下载，直接通过bash ./install.sh下载好了相关的包
接着进行了python Main.py --data-name USAir
以上是运行的最后几行的结果
再次感谢您的回复，谢谢
