### ISSUE TITLE
The use of the network

### ISSUE THREAD

**Issue by hrbwzq** [muhanzhang/SEAL#29]
I get a new graph and i want to add some edges. I have already trained this network but how i can use this trained network to predict links in my graph.  And see the result.  I want to konw changes of my graph. Thank you so much.

**Comment by muhanzhang** [comment]
Hi, once you have trained the GNN, you can save the model using "torch.save()", generate enclosing subgraphs for test links using "links2subgraphs()", and then apply the GNN to the test subgraphs to make link predictions. This requires some coding. I might add this inference framework in the near future. Please keep updated.

**Comment by hrbwzq** [comment]
thank you so much for your help. best wishes.


 
---Original---

**Comment by muhanzhang** [comment]
Hi,
I have added support of the inference framework, please see ce09780a894f33af8f8c81492167ff14c3b4d51e and the new README.md. Let me know if you have other questions.

**Comment by hrbwzq** [comment]
thank you so much. i will try this model with my data,
