### ISSUE TITLE
DGCNN

### ISSUE THREAD

**Issue by XuandongZhao** [muhanzhang/SEAL#3]
In order to use this code, shell I download pytorch_DGCNN first? And the DGCNN is based on structure2vec, so could you please simplify the dependency and I believe DGCNN will become a benchmark on graph deep learning! Thanks a lot!

**Comment by muhanzhang** [comment]
Hi, yes, you need to download and install pytorch_DGCNN first. Thanks for your advice for simplifying the dependencies. I'll try to write a script to automate the installation steps. Currently, please first follow the instruction guide to install it. Thanks!

**Comment by muhanzhang** [comment]
Hi, please download the latest version and use "bash ./install.sh" to automatically install all dependencies.
