### ISSUE TITLE
Reproduce the experiment in the paper

### ISSUE THREAD

**Issue by jianz94** [muhanzhang/SEAL#30]
I want to reproduce the experiments in the paper Link Prediction Based on Graph Neural Networks. However, I cannot get the sota results recorded in the paper. Take USAir for example, I run python Main.py --data-name  USAir --hop 'auto' --test-ratio 0.1 and get best accuracy at 0.92. Are there any special settings that I ignore? Thanks.

**Comment by muhanzhang** [comment]
Hi, 
In link prediction, we usually focus more on AUC results. The reported results in the paper are also AUC instead of accuracy.

**Comment by jianz94** [comment]
I found the accuracy in the appendices. In Appendix F, the AP values are very close to AUC. So I just wonder if I missed some important settings. By the way, how do you calculate AP of heuristic methods since they provide the probability of link existence rather than a definite classification result?
