### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by giuliacassara** [muhanzhang/SEAL#34]
Hi, this is a such an interesting paper! 
I want to train SEAL - Python version -  to a specific dataset, e.g. The Human Interactome. I saw that the data is expressed in .mat form composed by net and group, for explicit feature, and in raw form which is just a .txt file. But most of the interactome data is in form with the protein-protein which is an alphanumeric name. How have you done the mapping between node name <-> node number?

**Comment by muhanzhang** [comment]
Thanks! For the PPI_subgraph dataset, I was using the one processed by node2vec, available at https://snap.stanford.edu/node2vec/. To map names to numbers, you can use a dict and counter, and go through all you names to build the mapping from 0 to # unique_names - 1, and then transform to the standard format.

**Comment by giuliacern** [comment]
Thank you for your answer.
I was also wondering, how do you sample the negatome? If I want to give a separate list of negative links, where should I modify the code? Because I want to extend this functionality to the project.

**Comment by muhanzhang** [comment]
Check this [line](https://github.com/muhanzhang/SEAL/blob/bb817748199f05313b6d31666c0396543180737d/Python/Main.py#L122) for where the negative sampling takes place. You can replace train_neg/test_neg with your own customized ones. Otherwise, they will be sampled from the network randomly.

**Comment by binonteji** [comment]
Can I use a custom network data set to run SEAL. Like... with extensions .csv, .tsv ?

**Comment by muhanzhang** [comment]
@binonteji Yes, as long as it saves the network in the same format the SEAL reads, i.e., each line contains two nodes (correspond to an observed link).

**Comment by binonteji** [comment]
Thanks for the answer!
