### ISSUE TITLE
GPU running

### ISSUE THREAD

**Issue by Amirhekmatshoar** [muhanzhang/SEAL#37]
Hello 
Excuse me, when i run the main.py with USAir, the code running on my CPU
How can i run SEAL on GPU
I installed CUDA, torch and DGCNN  too.
thanks

**Comment by muhanzhang** [comment]
Hi, by default SEAL should run on GPU, unless you specify "--no-cuda". Can you test whether your other programs (such as DGCNN) can run on cuda?

**Comment by joc32** [comment]
Try using the PyTorch's Geometric implementation of SEAL, works for GPU (Colab).
