### ISSUE TITLE
dilibgnn.so error

### ISSUE THREAD

**Issue by unityRadman** [muhanzhang/SEAL#38]
hello
when i run the main.py i have error like this:
pythonw.exe - Bad Image
E: SEAL-master pytorch DGCNN\lib build\dilibgnn.so is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status Oxc000012f.
what should i do?

**Comment by muhanzhang** [comment]
Looks like you are running it on windows. Please refer to https://github.com/muhanzhang/pytorch_DGCNN/issues/27 or https://github.com/muhanzhang/pytorch_DGCNN/issues/13 for how to run DGCNN in windows.
