### ISSUE TITLE
AttributeError: module 'node2vec' has no attribute 'Graph'

### ISSUE THREAD

**Issue by xihairanfeng** [muhanzhang/SEAL#39]
当我尝试python Main.py --data-name NS --test-ratio 0.5 --hop 'auto' --use-embedding出现了这错误
以下是我的完整的错误报告（包括我自己添加的打印出A的结果）
====== begin of gnn configuration ======
| msg_average = 0
======   end of gnn configuration ======
Namespace(all_unknown_as_negative=False, batch_size=50, cuda=True, data_name='NS', hop='auto', max_nodes_per_hop=None, max_train_num=100000, no_cuda=False, no_parallel=False, only_predict=False, save_model=False, seed=1, test_name=None, test_ratio=0.5, train_name=None, use_attribute=False, use_embedding=True)
sampling negative links for train and test
Traceback (most recent call last):
  File "Main.py", line 138, in <module>
    embeddings = generate_node2vec_embeddings(A, 128, True, train_neg)
  File "/home/czw/SEAL/Python/util_functions.py", line 216, in generate_node2vec_embeddings
    G = node2vec.Graph(nx_G, is_directed=False, p=1, q=1)
AttributeError: module 'node2vec' has no attribute 'Graph'
(base) czw@sy-NF5280M5:~/SEAL/Python$ python Main.py --data-name NS --test-ratio 0.5 --hop 'auto' --use-embedding
====== begin of gnn configuration ======
| msg_average = 0
======   end of gnn configuration ======
Namespace(all_unknown_as_negative=False, batch_size=50, cuda=True, data_name='NS', hop='auto', max_nodes_per_hop=None, max_train_num=100000, no_cuda=False, no_parallel=False, only_predict=False, save_model=False, seed=1, test_name=None, test_ratio=0.5, train_name=None, use_attribute=False, use_embedding=True)
sampling negative links for train and test
  (1588, 0)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (5, 3)	1.0
  (1, 4)	1.0
  (5, 4)	1.0
  (1, 5)	1.0
  (3, 5)	1.0
  (4, 5)	1.0
  (7, 6)	1.0
  (8, 6)	1.0
  (10, 6)	1.0
  (6, 7)	1.0
  (6, 8)	1.0
  (9, 8)	1.0
  (10, 8)	1.0
  (1423, 8)	1.0
  (1531, 8)	1.0
  (8, 9)	1.0
  (10, 9)	1.0
  (6, 10)	1.0
  (8, 10)	1.0
  (9, 10)	1.0
  (12, 11)	1.0
  (1047, 11)	1.0
  :	:
  (336, 1571)	1.0
  (630, 1571)	1.0
  (1569, 1571)	1.0
  (1570, 1571)	1.0
  (1572, 1571)	1.0
  (336, 1572)	1.0
  (630, 1572)	1.0
  (1571, 1572)	1.0
  (782, 1573)	1.0
  (1575, 1574)	1.0
  (1577, 1574)	1.0
  (1574, 1575)	1.0
  (1576, 1575)	1.0
  (1575, 1576)	1.0
  (1577, 1576)	1.0
  (1574, 1577)	1.0
  (1576, 1577)	1.0
  (1583, 1582)	1.0
  (1582, 1583)	1.0
  (1586, 1584)	1.0
  (1584, 1586)	1.0
  (75, 1587)	1.0
  (521, 1587)	1.0
  (0, 1588)	1.0
  (1083, 1588)	1.0
Traceback (most recent call last):
  File "Main.py", line 138, in <module>
    embeddings = generate_node2vec_embeddings(A, 128, True, train_neg)
  File "/home/czw/SEAL/Python/util_functions.py", line 216, in generate_node2vec_embeddings
    G = node2vec.Graph(nx_G, is_directed=False, p=1, q=1)
AttributeError: module 'node2vec' has no attribute 'Graph'

btw，我使用readme.md其他的类型的跑代码运行是可以顺利跑通的。

实际上我测试了python Main.py --train-name PB_train.txt --test-name PB_test.txt --hop 1这个，是可以正确运行的，包括我自己定义了对应的数据集也是可以正确取得结果的。但是我加上--use-embedding就会出现和这个一样的错误，最后我才直接测试了python Main.py --data-name NS --test-ratio 0.5 --hop 'auto' --use-embedding出现了这样的结果，打印出来的A的形式是一样的。不知道哪里出现了问题

**Comment by xihairanfeng** [comment]
> 当我尝试python Main.py --data-name NS --test-ratio 0.5 --hop'auto'--use-embedding出现了这错误
> 以下是我的完整的错误报告（包括我自己添加的打印出A的结果）
> ====== gnn配置开始======
> | msg_average = 0
> ====== gnn配置结束======
> 命名空间（all_unknown_as_negative = False，batch_size = 50，cuda = True，data_name ='NS'，hop ='auto'，max_nodes_per_hop = None，max_train_num = 100000，no_cuda = False，no_parallel = False，only_predict = False，save_model = False，seed = 1，test_name = None，test_ratio = 0.5，train_name = None，use_attribute = False，use_embedding = True）
> 为火车和测试采样负链接
> 追溯（最近一次调用）：
> 文件“ Main.py”，第138行，
> 嵌入= generate_node2vec_embeddings（A，128，True，train_neg）
> 在generate_node2vec_embeddings中的文件“ /home/czw/SEAL/Python/util_functions.py”，第216行
> G = node2vec.Graph（nx_G，is_directed = False，p = 1，q = 1）
> AttributeError：模块'node2vec'没有属性'Graph'
> （base）czw @ sy-NF5280M5：〜/ SEAL / Python $ python Main.py --data-name NS --test-ratio 0.5 --hop'auto'--use-embedding
> ===== = gnn配置开始======
> | msg_average = 0
> ====== gnn配置结束======
> 命名空间（all_unknown_as_negative = False，batch_size = 50，cuda = True，data_name ='NS'，hop ='auto'，max_nodes_per_hop = None，max_train_num = 100000，no_cuda = False，no_parallel = False，only_predict = False，save_model = False，seed = 1，test_name = None，test_ratio = 0.5，train_name = None，use_attribute = False，
> 训练和测试的负链接采样
> （1588，0）1.0
> （4，1）1.0
> （5，1）1.0
> （5，3）1.0
> （1，4）1.0
> （5，4）1.0
> （1，5）1.0
> （ 3，5）1.0
> （4，5）1.0
> （7，6）1.0
> （8，6）1.0
> （10，6）1.0
> （6，7）1.0
> （6，8）1.0
> （9，8）1.0
> （10， 8）1.0
> （1423，8）1.0
> （1531，8）1.0
> （8，9）1.0
> （10，9）1.0
> （6，10）1.0
> （8，10）1.0
> （9，10）1.0
> （12，11） 1.0
> （1047，11）1.0
> ：：（
> 336，1571）1.0
> （630，1571）1.0
> （1569，1571）1.0
> （1570，1571）1.0
> （1572，1571）1.0
> （336，1572）1.0
> （630，1572）1.0
> （1571，1572）1.0
> （782，1573）1.0
> （1575，1574）1.0
> （1577，1574）1.0
> （1574，1575）1.0
> （1576，1575）1.0
> （1575） ，1576）1.0
> （1577，1576）1.0
> （1574，1577）1.0
> （1576，1577）1.0
> （1583年，1582年）1.0
> （1582年，1583）1.0
> （1586，1584）1.0
> （1584，1586）1.0
> （75，1587 ）1.0
> （521，1587）1.0
> （0，1588）1.0
> （1083，1588）1.0
> 回溯（最近最后调用）：
> 文件“Main.py”，管线138，在
> 嵌入物= generate_node2vec_embeddings（A，128，诚然，train_neg ）
> 在generate_node2vec_embeddings中的文件“ /home/czw/SEAL/Python/util_functions.py”，第216行
> G = node2vec.Graph（nx_G，is_directed = False，p = 1，q = 1）
> AttributeError：模块'node2vec'没有属性'图形'
> 
> btw，我使用readme.md其他的类型的跑代码运行是可以顺利跑通的。
> 
> 实际上我测试了python Main.py --train-name PB_train.txt --test-name PB_test.txt --hop 1这个，是可以正确运行的，包括我自己定义了对应的数据集也是可以正确取得结果的。但是我加上--use-embedding就会出现和这个一样的错误，最后我才直接测试了python Main.py --data-name NS --test-ratio 0.5 --hop'auto'- -use-embedding出现了这样的结果，打印出来的A的形式是一样的。不知道哪里出现了问题

具体的话，我认为是在如下地方的图出现了问题
def generate_node2vec_embeddings(A, emd_size=128, negative_injection=False, train_neg=None):
    if negative_injection:
        row, col = train_neg
        A = A.copy()
        A[row, col] = 1  # inject negative train
        A[col, row] = 1  # inject negative train
    nx_G = nx.from_scipy_sparse_matrix(A)
不知道啥原因导致nx_G没有生成？

**Comment by xihairanfeng** [comment]
> > 当我尝试python Main.py --data-name NS --test-ratio 0.5 --hop'auto'-use-embedding出现了这错误
> > 以下是我的完整的错误报告（包括我自己添加的打印出A的结果）
> > ====== gnn配置开始====== 
> > | msg_average = 0 
> > ====== gnn配置结束====== 
> > 命名空间（all_unknown_as_negative = False，batch_size = 50，cuda = True，data_name =“ NS”，hop =“ auto”，max_nodes_per_hop = None，max_train_num = 100000，no_cuda = False，no_parallel = False，only_predict = False，save_model = False，seed = 1，test_name = None，test_ratio = 0.5，train_name = None，use_attribute = False，use_embedding = True）
> > 为火车和测试采样负链接
> > 进入（最近一次调用）：
> > 文件“ Main.py”，第138行，
> > 嵌入= generate_node2vec_embeddings（A，128，True，train_neg）
> > 在generate_node2vec_embeddings中的文件“ /home/czw/SEAL/Python/util_functions.py”，第216行
> > G = node2vec.Graph（nx_G，is_directed = False，p = 1，q = 1）
> > AttributeError：模块'node2vec'没有属性'Graph' 
> > （基本）czw @ sy-NF5280M5：〜/ SEAL / Python $ python Main.py --data-name NS --test-ratio 0.5 --hop'auto'-use-embedding 
> > ===== = gnn配置开始====== 
> > | msg_average = 0 
> > ====== gnn配置结束====== 
> > 命名空间（all_unknown_as_negative = False，batch_size = 50，cuda = True，data_name =“ NS”，hop =“ auto”，max_nodes_per_hop = None，max_train_num = 100000，no_cuda = False，no_parallel = False，only_predict = False，save_model = False，seed = 1，test_name = None，test_ratio = 0.5，train_name = None，use_attribute = False，
> > 训练和测试的负链接采样
> > （1588，0 ）1.0 
> > （4，1）1.0 
> > （5，1）1.0 
> > （5，3）1.0 
> > （1，4）1.0 
> > （5，4）1.0 
> > （1，5）1。
> > （3，5）1.0 
> > （4，5）1.0 
> > （7，6）1.0 
> > （8，6）1.0 
> > （10，6）1.0 
> > （6，7）1.0 
> > （6，8）1.0 
> > （9，8）1.0 
> > （10 ，8）1.0 
> > （1423，8）1.0 
> > （1531，8）1.0 
> > （8，9）1.0 
> > （10，9）1.0 
> > （6，10）1.0 
> > （8，10）1.0 
> > （9，10）1.0 
> > （12，11） ）1.0 
> > （1047，11）1.0 
> > ：：（
> > 336，1571）1.0 
> > （630，1571）1.0 
> > （1569，1571）1.0 
> > （1570，1571）1.0 
> > （1572，1571）1.0 
> > （336，1572）1.0 
> > （630，1572） ）1.0 
> > （1571，1572）1.0 
> > （782，1573）1.0 
> > （1575，1574）1.0 
> > （1577，1574）1.0 
> > （1574，1575）1.0 
> > （1576，1575）1.0 
> > （1575），1576）1.0 
> > （1577，1576） 1.0
> > （1574，1577）1.0 
> > （1576，1577）1.0 
> > （1583年，1582年）1.0 
> > （1582年，1583）1.0 
> > （1586，1584）1.0 
> > （1584，1586）1.0 
> > （75，1587）1.0 
> > （521，1587） 1.0 
> > （0，1588）1.0 
> > （1083，1588）1.0 
> > 回溯（最近最后一次调用）：
> > 文件“ Main.py”，管线138，在
> > 嵌入物= generate_node2vec_embeddings（A，128，诚然，train_neg）
> > 在generate_node2vec_embeddings中的文件” /home/czw/SEAL/Python/util_functions.py”，第216行
> > G = node2vec.Graph（nx_G，is_directed = False，p = 1，q = 1）
> > AttributeError：模块'node2vec'没有属性'图形'
> > btw，我使用readme.md其他的类型的跑代码运行是可以顺利跑通的。
> > 实际上我测试了python Main.py --train-name PB_train.txt --test-name PB_test.txt --hop 1这个，是可以正确运行的，包括我自己定义了对应的数据集也是可以正确取得结果的。但是我加上--use-embedding就会出现和这个一样的错误，最后我才直接测试了python Main.py --data-name NS --test-ratio 0.5 --hop'auto'- -use-embedding出现了这样的结果，打印出来的A的形式是一样的。不知道哪里出现了问题
> 
> 特定的话，我认为是在以下地方的图出现了问题
> def generate_node2vec_embeddings（A，emd_size = 128，negative_injection = False，train_neg = None）：
> 如果negative_injection：
> row，col = train_neg
> A = A.copy（）
> A [行，col] = 1＃注入负 序列
> A [col，row] = 1＃注入负
> 序列nx_G = nx.from_scipy_sparse_matrix（A）
> 不知道啥原因导致nx_G没有生成？

然后我也试了删除。pyc文件的做法，由于我在服务器没有管理员权限，因此我只能手动删除项目的。pyc文件，不仅仅是在python文件里面的，也包括pytorch_DGCNN里面的pyc文件。我服务器的文件夹这个里面只有另一个项目，因此我以为另一个项目的pyc文件会影响，于是我连另一个项目的整个项目都删除了。并且重新下载了该项目文件以及pytorch_DGCNN，还是不能运行这条python Main.py --data-name NS --test-ratio 0.5 --hop'auto'--use-embedding，出错的原因还是一样的。其他的方式执行python Main.py是可以行的通的。另外我是使用的Anaconda3

**Comment by muhanzhang** [comment]
Hi, 请问你用的是SEAL/Python/software/下面自带的node2vec吗？ AttributeError: module 'node2vec' has no attribute 'Graph' 说明import的node2vec没有Graph class。我测试了一下我的没有出现这个问题，但是出现了一个https://github.com/aditya-grover/node2vec/issues/35 中描述的问题。我已经更新了相关代码。

**Comment by xihairanfeng** [comment]
> Hi, 请问你用的是SEAL/Python/software/下面自带的node2vec吗？ AttributeError: module 'node2vec' has no attribute 'Graph' 说明import的node2vec没有Graph class。我测试了一下我的没有出现这个问题，但是出现了一个[aditya-grover/node2vec#35](https://github.com/aditya-grover/node2vec/issues/35) 中描述的问题。我已经更新了相关代码。

是的，如果您是可以执行的话，那么一定是我这边的配置文件出现了问题（因为其他几种不涉及use-embedding的都是可以顺利执行的），我将项目相关的文件重新删除在重新试试

**Comment by xihairanfeng** [comment]
> > Hi, 请问你用的是SEAL/Python/software/下面自带的node2vec吗？ AttributeError: module 'node2vec' has no attribute 'Graph' 说明import的node2vec没有Graph class。我测试了一下我的没有出现这个问题，但是出现了一个[aditya-grover/node2vec#35](https://github.com/aditya-grover/node2vec/issues/35) 中描述的问题。我已经更新了相关代码。
> 
> 是的，如果您是可以执行的话，那么一定是我这边的配置文件出现了问题（因为其他几种不涉及use-embedding的都是可以顺利执行的），我将项目相关的文件重新删除在重新试试

我重新移除了服务器上所有的文件进行了重新的配置环境，执行这个python Main.py --data-name NS --test-ratio 0.5 --hop'auto'- -use-embedding的时候结果成功通过了您新改的代码，不过这里有一个小的torch包没有导入，自己插入后通过运行。
仔细回想一下，我通过anaconda的环境，跑过一次关于node2vec（我的是一个包跑的并且是和这个不在同一个项目里面），不知道是不是这个原因导致我的配置文件出现了问题。反正在删除所有项目并且重新安装anaconda3之后，重新跑代码可以顺利通过，再次谢谢您更新的代码以及回复。
