### ISSUE TITLE
continue waiting for output?

### ISSUE THREAD

**Issue by XuSShuai** [muhanzhang/SEAL#4]
it' a great job! I want to know in the status below, what should i going to do, waiting or some error already happened.

![_20181020200206](https://user-images.githubusercontent.com/29543183/47255394-0a28bd80-d4a3-11e8-98a7-43347feca943.png)

**Comment by muhanzhang** [comment]
Hi, thanks for pointing this out. I have removed the _pdb.set_trace()_ break point. I included it for debugging. You can delete the line 64 in _util_functions.py_ and it should work.

**Comment by XuSShuai** [comment]
> Hi, thanks for pointing this out. I have removed the _pdb.set_trace()_ break point. I included it for debugging. You can delete the line 64 in _util_functions.py_ and it should work.

thanks for your reply very much.  i think i need spend time to read your code carefully, it taught me a lot.

**Comment by XuSShuai** [comment]
problem solved.
