### ISSUE TITLE
EColi .txt file

### ISSUE THREAD

**Issue by joc32** [muhanzhang/SEAL#41]
Hi Muhan, 

I am using the datasets you provided in the repo, however I cannot find the Ecoli dataset in .txt version. Do you know where I could find it or I am looking somewhere wrong?

Thanks,
Jozef

**Comment by muhanzhang** [comment]
Hi Jozef,

The Ecoli dataset doesn't have a .txt version. I prepared it directly from the metabolic network of E.coli.

**Comment by joc32** [comment]
I understand. Well, suppose you have it stored in a variable at some point of your code (edge-list format), wouldn't it be possible if you had uploaded it to GitHub for the sake of completion? (in networkx gpickle format for example).

**Comment by muhanzhang** [comment]
Of cousrse. I mean it is directed saved in .mat, in "https://github.com/muhanzhang/SEAL/blob/master/Python/data/Ecoli.mat".
