### ISSUE TITLE
Link prediction with multiple node types

### ISSUE THREAD

**Issue by RemingtonKim** [muhanzhang/SEAL#42]
Hey there Muhan,

I was wondering if SEAL worked on graphs with multiple types of nodes (i.e. heterogeneous networks). Take the graph below, for example:
![image](https://user-images.githubusercontent.com/53198857/92294133-1c753e80-eef7-11ea-8bc9-8c8ff79a65c1.png)
If I would like to my GNN to predict only if there is a link between between green circles and blue triangles, would I just make sure that the central nodes *x* and *y* are blue triangles and green circles, or vice versa during the subgraph extraction process?

Thanks!

**Comment by muhanzhang** [comment]
Yes! With some modifications of the GNN used SEAL is able to predict links in heterogeneous graphs. Actually matrix completion is such an example with two node types and five edge types, for which you can refer to my another paper: https://github.com/muhanzhang/IGMC

**Comment by RemingtonKim** [comment]
Thank you for the info!
