### ISSUE TITLE
Node Attributes and Edge Attributes

### ISSUE THREAD

**Issue by LIANGKE23** [muhanzhang/SEAL#46]
Hi, I am trying to use the SEAL to figure out link prediction problem on multi-relational graphs. And I want to ask you two questions:
1. _**parser.add_argument('--use-attribute', action='store_true', default=False, help='whether to use node attributes')**_
Is the code above for adding node attributes in training process? 
And For example, in my own dataset they are 1000 nodes, divided into 6 classes. I also want to use the class information for training the model. 
How can I build the file (attribute.txt/attribute.mat)? What is the format of the file for adding node attributes?

2. You model can only predict whether two nodes have link or not, am I right? Is there any way to extend it to multi relational link prediction?

Thanks

**Comment by muhanzhang** [comment]
1. Yes. To use node class as attribute, you can prepare a `group` variable in your `.mat` graph, where each row in the `group` contains the one-hot-encoding of this node's class. You can refer to `PPI_subgraph.mat` for an example.

2. SEAL is easy to extend to multi-relational link prediction. You can use R-GCN as the GNN to handle multiple edge types, and replace the binary loss to multi-class loss. For example, see SEAL's sister model, [IGMC](https://github.com/muhanzhang/IGMC), for recommender systems.

**Comment by LIANGKE23** [comment]
Thanks!
I have checked PPI-subgraph.mat, it is shown below.
![图片](https://user-images.githubusercontent.com/55468383/97821811-ba7c4f80-1c81-11eb-9454-06ac512d3aa2.png)
There are 3889 rows and 49 collumns. In my understanding, it means there are 3889 nodes, and 49 kinds of attributes for all the nodes. For example, in the figure shown above, node 4 has two features which are feature 1 and feature 8. Am I right?

**Comment by muhanzhang** [comment]
Yes!

**Comment by LIANGKE23** [comment]
> 
> 
> Yes!

I have a follow-up question here.

When we do link prediction problem
