### ISSUE TITLE
怎样在您的代码里面添加一个指标Precision

### ISSUE THREAD

**Issue by xihairanfeng** [muhanzhang/SEAL#48]
如何在您的代码里面的最终结果中在添加一个指标Precision？

**Comment by muhanzhang** [comment]
你可以在pytorch_DGCNN里面加一个输出average precision的选项(print_ap)，然后类似计算[auc](https://github.com/muhanzhang/pytorch_DGCNN/blob/50f504131ca66382f3f078ae98e59aa3ae35b795/main.py#L183)一样，添加一个计算ap的block，并返还给SEAL。

**Comment by xihairanfeng** [comment]
好的，这问题已经解决，忘了给您回信，非常感谢
