### ISSUE TITLE
Data Leakage Issue

### ISSUE THREAD

**Issue by remingtonkim** [muhanzhang/SEAL#49]
Hi there,

I just had a question about data leakage regarding SEAL. Say that there are two subgraphs where one is in the training set and the other is in the testing set. They happen to overlap a bit (i.e. share some of the same nodes and edges), but they are distinct subgraphs, and the link trying to be predicted is different between the two of them. If I am understanding correctly, this is not a data leakage issue because SEAL treats each subgraph as its own entity and does not care about the subgraphs position in the larger network, and DRNL is done on individual subgraphs. Thus, they *happen* to overlap in the larger network, but that has no implications on SEAL's performance, so it is okay for one of them to be in the testing set and the other to be in the training set. Sorry if this is a basic question; I just wanted to clarify my thinking.

Cheers!

**Comment by muhanzhang** [comment]
Yes! Your understanding is correct!

**Comment by remingtonkim** [comment]
Got it! Thank you very much!
