### ISSUE TITLE
 A.eliminate_zeros()  # make sure the links are masked when using the sparse matrix in scipy-1.3.x AttributeError: 'numpy.ndarray' object has no attribute 'eliminate_zeros'

### ISSUE THREAD

**Issue by Macvh** [muhanzhang/SEAL#53]
A.eliminate_zeros()  # make sure the links are masked when using the sparse matrix in scipy-1.3.x
AttributeError: 'numpy.ndarray' object has no attribute 'eliminate_zeros'
张博士，您好！使用python3.8执行SEAL遇到错误，我也把scipy包版本降下来了依旧报错，不知如何解决！谢谢！

**Comment by muhanzhang** [comment]
A应该是一个scipy sparse matrix，而不是np.ndarray。请检查一下A 或 net 是哪里被变更成np.ndarray的？

**Comment by Macvh** [comment]
好的，谢谢您的回复，我先是通过直接将A的类型再转为了scirpy的sparse matrix，暂时解决了这个问题，我现在再检查看看哪里它类型变更了，谢谢您
