### ISSUE TITLE
PrepareFeatureLabel throwing out of bounds error

### ISSUE THREAD

**Issue by adg-git** [muhanzhang/SEAL#54]
Hi, thanks for sharing your code and related paper . I tried training it on my own data and saved the model and then tried to predict link probability using the command below. Please could you throw some light on what could have caused the error below 

python Main.py --data-name DATA --train-name DATA_train.txt --test-name DATA_test.txt --hop 1 --use-attribute --max-nodes-per-hop 50 --max-train-num 50000 --only-predict
====== begin of gnn configuration ======
| msg_average = 0
======   end of gnn configuration ======
Namespace(all_unknown_as_negative=False, batch_size=50, cuda=False, data_name='DATA', hop='1', max_nodes_per_hop='50', max_train_num=50000, no_cuda=False, no_parallel=False, only_predict=True, save_model=False, seed=1, test_name='DATA_test.txt', test_ratio=0.1, train_name='DATA_train.txt', use_attribute=True, use_embedding=False)
sampling negative links for train and test
Enclosing subgraph extraction begins...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [02:18<00:00,  2.18s/it]
Time eplased for subgraph extraction: 147.22653317451477s
# test: 62717
Initializing DGCNN
Traceback (most recent call last):
  File "Main.py", line 190, in <module>
    predictions.append(classifier(batch_graph)[0][:, 1].exp().cpu().detach())
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/Code/SEAL/Python/../../pytorch_DGCNN/main.py", line 119, in forward
    feature_label = self.PrepareFeatureLabel(batch_graph)
  File "~/Code/SEAL/Python/../../pytorch_DGCNN/main.py", line 90, in PrepareFeatureLabel
    node_tag.scatter_(1, concat_tag, 1)
RuntimeError: index 38 is out of bounds for dimension 1 with size 33

**Comment by muhanzhang** [comment]
From the message, it seems your concat_tag contains an node tag of 38 which is larger than node_tag's dimension of 33. The node_tag's dimension is set in [cmd_args.feat_dim](https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/Python/Main.py#L211). Can you manually set it to a number larger than 38, e.g., 50 or 100?  The reason is because your testing graphs might contain node labels larger than the maximum node label inferred from the training data.

**Comment by adg-git** [comment]
Yes, that could easily be the case with my test dataset.  I will try your suggestion above.  Thanks so much for the quick response.

**Comment by adg-git** [comment]
I set  cmd_args.feat_dim=100 and everything ran without error. I have another follow-up question, is this node label that you referred above the DRNL labels? I am asking because there are thousands of nodes in the graph dataset.

**Comment by muhanzhang** [comment]
Right. They are the DRNL labels.

**Comment by adg-git** [comment]
Also, does SEAL work for networks with edge weights?

**Comment by muhanzhang** [comment]
The SEAL framework surely can support edge weights by modifying the default DGCNN to incorporate edge weights during message passing. This repository does not support edge weights directly. You can refer to https://github.com/facebookresearch/SEAL_OGB for a more advanced implementation of SEAL which supports edge weights naturally.

**Comment by adg-git** [comment]
I see, but the API supported by SEAL_OGB seems to be different than SEAL. Does SEAL_OGB support save-model and then predict-only like SEAL ?

**Comment by muhanzhang** [comment]
SEAL_OGB supports save-model but does not support predict-only.

**Comment by adg-git** [comment]
Will it be easier to change the code for SEAL to make DGCNN work for graphs with edge weights than try to make SEAL_OGB run on custom data not part of OGB since SEAL_OGB does not support API for inference with saved model?

**Comment by muhanzhang** [comment]
I still recommend developing based on SEAL_OGB, as it uses the flexible pytorch_geometric library and has better a scalability than the original implementation due to a series of efficiency optimizations. To add predict-only function, just load your saved model through `model.load_state_dict(torch.load(your_model_save_path))` and skip the training part. You may also submit a feature request describing your cases.

**Comment by adg-git** [comment]
Thanks for the suggestions. That was super helpful.
