### ISSUE TITLE
Meet index out of range error when executing shortest path

### ISSUE THREAD

**Issue by junjun1023** [muhanzhang/SEAL#55]
Hi, I was using your framework to do link predictions on my graphs, but it raised index out of range error when executing the line shortest path.

I think it may because of the isolated node in graphs or other reasons.

Is there any using constraints of your method like need to remove isolated node?

Thank you for your time.

**Comment by muhanzhang** [comment]
Hi! The isolated nodes are not likely the reason because SEAL can handle infinity values in distances. Can you paste the error message and other more concrete details?

**Comment by junjun1023** [comment]
Here is the error message.

```<ipython-input-79-2e9ca32335f0> in process(self)
     81 
     82         train_pos_list = self.extract_enclosing_subgraphs(
---> 83             train_pos_edge, train_pos_edge, 1)
     84         train_neg_list = self.extract_enclosing_subgraphs(
     85             train_neg_edge, train_pos_edge, 0)

<ipython-input-79-2e9ca32335f0> in extract_enclosing_subgraphs(self, link_index, edge_index, y)
    125             # Calculate node labeling.
    126             z = self.drnl_node_labeling(sub_edge_index, src, dst,
--> 127                                         num_nodes=sub_nodes.size(0))
    128 
    129             data = Data(x=self.data.x[sub_nodes], z=z,

<ipython-input-79-2e9ca32335f0> in drnl_node_labeling(self, edge_index, src, dst, num_nodes)
    147 
    148         dist2src = shortest_path(adj_wo_dst, directed=False, unweighted=True,
--> 149                                  indices=src)
    150         dist2src = np.insert(dist2src, dst, 0, axis=0)
    151         dist2src = torch.from_numpy(dist2src)

_shortest_path.pyx in scipy.sparse.csgraph._shortest_path.shortest_path()

_shortest_path.pyx in scipy.sparse.csgraph._shortest_path.dijkstra()

ValueError: indices out of range 0...N
```

Using result of `k_hop_subgraph` to label node feature, I also printed out the `adj_wo_src.shape[0]` or `adj_wo_shape[0]` and I got `0`.
I'm not sure what caused the error.
Do you have any idea?

Here is how I handle my graph:

1. I have a list of node pairs with label 0/1, which show the node pair linked or not.
2. I split the positive node pairs and negative node pairs to train/valid instead of using negative sampling.
3. Then I fed the node pairs to `extract_enclosing_subgraphs` function.

 Thank you for your time!!!!

**Comment by junjun1023** [comment]
I found that the error was raised when `src` and `dst` are the same, and I think the error may be related to `self_loop`?

**Comment by muhanzhang** [comment]
I see that you are using the pytorch_geometric version. For your question: right, when `src` and `dst` are the same and the node is isolated, the extracted subgraph `adj` becomes a 1 * 1 matrix. Then the `adj_wo_src` becomes 0 * 0, where shortest_path fails. This means DRNL cannot handle isolated identical src and dst cases. If you confirm you want to predict such links, you can manually filter out these links and give the single node a label 1 instead of calling the DRNL.
