### ISSUE TITLE
ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by huizhang1032** [muhanzhang/SEAL#57]
张博士：
您好！

> 我是在校学生，最近在学习链路预测方面的研究，在网上搜索到您的论文，并且想运行您的代码，理解该算法原理，在运行过程中出现了标题那种错误，网上搜寻一无所获，想请问一下您这个mian 是什么？

**Comment by muhanzhang** [comment]
你好。你需要安装pytorch_DGCNN，可以按照README运行 ”bash ./install.sh“，或自己安装https://github.com/muhanzhang/pytorch_DGCNN。

**Comment by huizhang1032** [comment]
我在window10操作系统  pycharm环境下  运行 ”bash ./install.sh“  以及安装pytorch_DGCNN，会出现系统不匹配的问题，这是什么缘故呢，这个代码是需要在Ubuntu系统下运行吗

**Comment by muhanzhang** [comment]
是的。win10下运行需手动安装pytorch_DGCNN

**Comment by huizhang1032** [comment]
https://github.com/muhanzhang/pytorch_DGCNN 里面也没有具体说明如何手动安装pytorch_DGCNN，而且里面还牵扯到，This implementation is based on Hanjun Dai's structure2vec graph backend. Under the "lib/" directory, type，安装说明大多是基于Ubuntu安装的，所以，我比较疑惑的是windows10环境的 安装

**Comment by huizhang1032** [comment]
https://github.com/muhanzhang/pytorch_DGCNN/issues/36#issuecomment-751946769  您在另一位网友的回答说，Pytorch_DGCNN does not support windows well.

**Comment by muhanzhang** [comment]
见https://github.com/muhanzhang/pytorch_DGCNN/issues/27

你可以在windows 10安装ubuntu sub system，然后剩下的参照README

**Comment by huizhang1032** [comment]
我另外安装了ubuntu system ，按照README说明 运用出来了，非常感谢！！！
