### ISSUE TITLE
sampling negative links 

### ISSUE THREAD

**Issue by amiduai** [muhanzhang/SEAL#65]
张博士，你好！最近拜读了您的论文，但是有些疑问，特来请教一下。

1.您的代码是从未知links中随机sample，然后作为negative links数据集，而且positive links和negative links是1：1的，对吗？

2 .按照1：1 进行sample是为了数据平衡吗？如果不用1：1的话，用1：2，1：3的话情况会怎么样呢？对于一些比较稀疏的图，它的任意两个结点没有边的概率应该要大于有边的概率，对于这种图是否需要调整比例呢？

3 .另外，假如未知中的links中sample出来的negative links正好是实际上是存在只是未被观测到的呢，这种情况是不是会对结果造成影响。如果有negative links的ground truth数据的话，结果是不是会更好呢？

**Comment by muhanzhang** [comment]
1. 对的。
2. 是为了数据平衡，也为了节约样本量。我没有深入研究过这个问题。可以1:N的sample，由于更多的negative samples，有可能performance更好。
3. 可能会，但是这是negative sampling的标准做法，比如node2vec也是随机sample。但是影响不会很大，考虑实际网络中大部分都是稀疏图，则随机sample的节点对大部分都是true negative links。如果有ground truth negative应该会更好，事实上在matrix completion里面我们用的就都是ground truth links，见https://github.com/muhanzhang/IGMC

**Comment by amiduai** [comment]
好的，谢谢解答!
