### ISSUE TITLE
Questions about the contents in txt and mat files.

### ISSUE THREAD

**Issue by zackzhou0814** [muhanzhang/SEAL#68]
Hello Dr.Zhang
I have a few questions about the dataset files.
1. Are the numbers in the txt files the index of two nodes with the same type? For example, the first row in USAir.txt: 118 201 0.1804. Does it mean it's the relationship between a node with label 118 a node with label 201? And 0.1804 is the probability that two nodes have a link?
2. In mat files, for example, the first row in USAir.mat: (132,1) 1, does it mean there is a link between node 132 and node 1, so there is a "1" that indicates it is a positive case?
3.  When should use txt and when we should use mat file, or it doesn't matter too much?

Thank you very much!

**Comment by muhanzhang** [comment]
Hi! In .txt, 118 201 0.1804 means node 118 and node 201 has a link (and the 0.1804 is ignored because not all datasets have link strengths). This txt is transformed to .mat to be used in SEAL. The .mat uses a sparse matrix data structure. (132,1) 1 means the entry (132,1) of the network matrix has value 1 (link).

**Comment by zackzhou0814** [comment]
Thank you for your reply, Dr.Zhang. You mentioned that txt is transformed to .mat to be used in SEAL, but I can still use the raw txt for training and testing in SEAL, is that correct?

**Comment by muhanzhang** [comment]
No. The network file must be .mat. See https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/Python/Main.py#L85.

**Comment by zackzhou0814** [comment]
Oh I see. So the txt files are still required, but they are not used directly for training and testing, they got transformed to .mat, then the neural network uses the transformed .mat files for training and testing tasks, is that correct? Sorry for more questions, and thank you for your replies again.
