### ISSUE TITLE
Error when trying to run my own datasets

### ISSUE THREAD

**Issue by zackzhou0814** [muhanzhang/SEAL#69]
Hello Dr.Zhang
I'm trying to use my own three datasets(in txt. format) on SEAL by the command: python Main.py --data-name PB --train-name train.txt --test-name train.txt --hop 1 (here, I don't have my test datasets yet so I just use training datasets to see if the program runs), but only one can successfully run, and other two gives errors like these:

sampling negative links for train and test
Enclosing subgraph extraction begins...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:01<00:00, 62.91it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 140, in parallel_worker
    return subgraph_extraction_labeling(*x)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 163, in subgraph_extraction_labeling
    nodes.remove(ind[1])
KeyError: 193/333 for the other dataset
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 160, in <module>
    train_graphs, test_graphs, max_n_label = links2subgraphs(
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 132, in links2subgraphs
    train_graphs = helper(A, train_pos, 1) + helper(A, train_neg, 0)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 118, in helper
    results = results.get()
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 193/333

I didn't modify the code, and part of my datasets looks like this, where each row is the link of two nodes.
10 130
10 131
30 19
30 137
30 393
37 10
37 33
37 38
37 46
37 48
37 49
37 50
37 56
37 60
37 61
37 65
37 83
37 90
37 126
37 145
37 151
37 159
37 197
37 219
37 221
37 263
37 266
37 267
37 287
37 354
42 60
42 61
42 106
42 305
42 320
42 367
44 32
44 67
44 128
44 352
47 46
52 23
52 31
52 32
52 60
52 61
52 66
52 78
52 94
52 95
52 96
52 98
52 99
52 102
52 103
52 110
52 111
52 112
52 190
52 193
52 212
52 221
52 222
52 231
52 307
52 320
52 344
52 352
52 354
52 367
52 474
52 477
54 11
54 14
54 18
54 19
54 23
54 34
54 46
54 64
54 67
54 73
54 104
54 105
54 126
54 137
54 157
54 185
54 195
54 198
54 202
54 273
54 287
54 288
54 344
54 372
54 382
54 393
58 60
58 61
59 10
60 25

Is there a specific format of the dataset I missed? It seems like there is a problem in subgraph labeling part based on the error message but I'm not sure why since I use the same way to construct the data for all three datasets. Thank you!

**Comment by muhanzhang** [comment]
Hi! In `File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 163, in subgraph_extraction_labeling
nodes.remove(ind[1])`, can you set a break point by `pdb.set_trace()` try to print `ind[1]` to see whether it is in `nodes`?

**Comment by zackzhou0814** [comment]
Hi Dr.Zhang
I have tried to set a breakpoint there, I tried both pdb.set_trace() and breakpoint(), and used the same command: python Main.py --data-name PB --train-name train.txt --test-name train.txt --hop 1 to run the program, but the program does not stop at the breakpoint  which means I can not choose any command from pdb for debugging. And it gives an error message like this: 

Namespace(all_unknown_as_negative=False, batch_size=50, cuda=True, data_name=None, hop='1', max_nodes_per_hop=None, max_train_num=100000, no_cuda=False, no_parallel=False, only_predict=False, save_model=False, seed=1, test_name='PB_test.txt', test_ratio=0.1, train_name='IncRNA_MirRNA_Links.txt', use_attribute=False, use_embedding=False)
sampling negative links for train and test
Enclosing subgraph extraction begins...
  0%|                                                                                                                                   | 0/63 [00:00<?, ?it/s]
> /home/tzhou/SEAL-master/SEAL/Python/util_functions.py(164)subgraph_extraction_labeling()
-> nodes.remove(ind[1])
(Pdb) 
> /home/tzhou/SEAL-master/SEAL/Python/util_functions.py(164)subgraph_extraction_labeling()
-> nodes.remove(ind[1])
(Pdb) 
> /home/tzhou/SEAL-master/SEAL/Python/util_functions.py(164)subgraph_extraction_labeling()
-> nodes.remove(ind[1])
(Pdb) 
> /home/tzhou/SEAL-master/SEAL/Python/util_functions.py(164)subgraph_extraction_labeling()
-> nodes.remove(ind[1])
(Pdb) 
> /home/tzhou/SEAL-master/SEAL/Python/util_functions.py(164)subgraph_extraction_labeling()
-> nodes.remove(ind[1])
(Pdb) 
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:01<00:00, 62.93it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 140, in parallel_worker
    return subgraph_extraction_labeling(*x)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 164, in subgraph_extraction_labeling
    nodes.remove(ind[1])
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 164, in subgraph_extraction_labeling
    nodes.remove(ind[1])
  File "/home/tzhou/anaconda3/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/tzhou/anaconda3/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 160, in <module>
    train_graphs, test_graphs, max_n_label = links2subgraphs(
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 132, in links2subgraphs
    train_graphs = helper(A, train_pos, 1) + helper(A, train_neg, 0)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 118, in helper
    results = results.get()
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
bdb.BdbQuit

I also tried to print out the variable nodes directly and it processed for some data but stoped later and returned the error as I mentioned at the first place.

**Comment by muhanzhang** [comment]
Hi! When debugging, you need to disable multiprocessing by appending "--no-parallel".

**Comment by zackzhou0814** [comment]
Dr.Zhang
I set a breakpoint under the nodes.remove(ind[1]), in this case, both target nodes should already be removed from nodes, so when I print nodes it returns set(). 
(Pdb) p ind[0]
217
(Pdb) p ind[1]
50
(Pdb) p nodes
set()

I also tried a breakpoint under nodes = [ind[0], ind[1]] + list(nodes), I tried to print nodes again and it returns [217,50], so I assume this is correct since both target nodes are in nodes. (since I'm using the same datasets for both training and testing, so it only returns [217,50] two nodes, which is the same case for PB_train.txt, so I assume it's not the issue).

However, one thing that I found is different between the dataset that can be run(PB_train) and the one that can not be run: when I manually print out the nodes without adding target nodes by print(list(nodes)) on PB_train, it immediately  returns a out of range error message, but when I run the code on my dataset, it first prints out a bunch of empty list, like:
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
Then throw an out-of-range error message. 

I also tried to manually print out ind[0], ind[1] and nodes after line nodes = [ind[0], ind[1]] + list(nodes), it returns a bunch of numbers and lists, but it eventually stops at some point and throws the error message I mentioned in the first place:
217
50
[217,50]
(other numbers and lists that I didn't paste here for saving space)
[116, 12]
124
147
[124, 147]
124
351
[124, 351]
186
48
[186, 48]
154
114
[154, 114]
228
24
[228, 24]
72
48
[72, 48]
72
189
[72, 189]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:01<00:00, 62.96it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 140, in parallel_worker
    return subgraph_extraction_labeling(*x)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 163, in subgraph_extraction_labeling
    nodes.remove(ind[1])
KeyError: 193
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 160, in <module>
    train_graphs, test_graphs, max_n_label = links2subgraphs(
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 132, in links2subgraphs
    train_graphs = helper(A, train_pos, 1) + helper(A, train_neg, 0)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 118, in helper
    results = results.get()
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 193

**Comment by muhanzhang** [comment]
**File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 163, in subgraph_extraction_labeling
nodes.remove(ind[1])
KeyError: 193**
means node 193 is not in `nodes`. Check whether you have a row with double 193 in your dataset. Otherwise, print step by step to see how the 193 is added to `nodes` and why it is not in `nodes` where it should be in (you can breakpoint only when you encounter ind[1]=193, no need to breakpoint for all).

**Comment by zackzhou0814** [comment]
That was the issue! I forgot that my dataset might have the case where the nodes have the same label and that's the reason that caused the program to crash. Thank you so much for your help and patience, Dr.Zhang!
