### ISSUE TITLE
Scores besides acc and auc

### ISSUE THREAD

**Issue by zackzhou0814** [muhanzhang/SEAL#70]
Hi Dr.Zhang
I'm wondering if you have implemented other scores besides acc and auc? I'm trying to implement the recall score, which is the ratio of correctly identified positive examples to all positive examples. I saw auc and acc were implemented by feeding graphs into the loop_dataset function, where the graphs are generated by links2subgraph. If I want to generate recall, do I need to modify these functions? Or there is an easier way to do it? Also, I can't find links2subgraph in the file, could you give some guidance, please? Thank you very much.

**Comment by muhanzhang** [comment]
To compute recall, you can modify the `CalcAUC` function to something like following (I didn't really run it):

    def CalcRecall(sim, test_pos, test_neg, threshold=0.5):
        pos_scores = np.asarray(sim[test_pos[0], test_pos[1]]).squeeze()
        neg_scores = np.asarray(sim[test_neg[0], test_neg[1]]).squeeze()
        probs = np.concatenate([pos_scores, neg_scores]).exp()
        predictions = probs > threshold
        labels = np.hstack([np.ones(len(pos_scores)), np.zeros(len(neg_scores))])
        recall = metrics.recall_score(labels, predictions)
        return recall

You may need to specify your threshold.

The links2subgraph code is [here](https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/Python/util_functions.py#L71).

**Comment by zackzhou0814** [comment]
Thanks for the suggestion! However, if I don't get it wrong, the CalcAUC and CalcACC functions are used to in Links2subgraphs function:
if val_auc_AA >= val_auc_CN:
            h = 2
            print('\033[91mChoose h=2\033[0m')
        else:
            h = 1
            print('\033[91mChoose h=1\033[0m')
which is used to determine the value of h, and I don't see they got used anywhere else.  So I assume the recall should be computed in loop_dataset function? Since it computes avg_loss which contains both AUC and ACC. But I could still be wrong, please correct me if I'm wrong, thank you very much!

**Comment by muhanzhang** [comment]
You are right. Then you need to calculate recall in the pytorch_DGCNN. You can write your recall computing function [here](https://github.com/muhanzhang/pytorch_DGCNN/blob/50f504131ca66382f3f078ae98e59aa3ae35b795/main.py#L180), similar to the above.
