### ISSUE TITLE
Command line argument for running facebook dataset

### ISSUE THREAD

**Issue by shhs29** [muhanzhang/SEAL#71]
Hi Dr. Zhang,

I wanted to understand the exact command that can replicate the results shown in the paper for [Facebook](https://snap.stanford.edu/data/ego-Facebook.html) dataset.

**Comment by muhanzhang** [comment]
Back in the paper, I actually used the MATLAB and Torch code to get the results. You can run the `case=2` [branch](https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/MATLAB/Main.m#L35) to do experiments on Facebook.  To use the python code, you may need to transform the MATLAB settings to python command lines. It should work on Facebook too.

**Comment by shhs29** [comment]
Hi Dr. Zhang,

Thanks a lot for your response. I will check the branch for more details.

Closing this issue as it is resolved.
