### ISSUE TITLE
Access the nodes and edges from the subgraph

### ISSUE THREAD

**Issue by zackzhou0814** [muhanzhang/SEAL#73]
Hi Dr.Zhang
I have been studying your code for a while, and I understand that you have a function called links2subgraph that generates the subgraphs that can be fed into the network. When I print out the train_graphs, it gives me a list that contains many objects like <util.GNNGraph object at 0x7f30f7ab5d30>, does it mean that it's a subgraph of one link? If it is the case, I want to get the actual nodes and edges from this graph. For example, I want [1,2,3,4], which are the nodes in a subgraph, and [(1,2),(3,4)] are the edges; how should I obtain these lists?  
Also, in the Classifier class, is the batch_graph(in the forward function) the train_graph/g_list? Just want to make sure I understand that correctly. Thank you very much!

**Comment by muhanzhang** [comment]
Yes, it is a subgraph of each link. The `GNNGraph` object is defined [here](https://github.com/muhanzhang/pytorch_DGCNN/blob/50f504131ca66382f3f078ae98e59aa3ae35b795/util.py#L41). It contains a networkx graph which can recover the node/edge information you need. The `batch_graph` is constructed [here](https://github.com/muhanzhang/pytorch_DGCNN/blob/50f504131ca66382f3f078ae98e59aa3ae35b795/main.py#L147). It contains a batch of graphs from `g_list`, not the full `g_list`, for mini-batch training.

**Comment by zackzhou0814** [comment]
Thank you very much for the clarification, that was very helpful! I still have one more question that I want to be clear about. In the paper, you mentioned that a network would take (A,X), where A is an adjacency matrix of a subgraph, and I'm looking for this matrix in your code, is it the edge_pairs in GNNGraph, or do we need to manually construct the matrix using the edges in the graph?  Thank you!
