### ISSUE TITLE
How to determine the index of the nodes in the enclosing subgraph?

### ISSUE THREAD

**Issue by XuSShuai** [muhanzhang/SEAL#8]
Hi~
From your paper, we can know that the GNN takes (A, X) as input, I have a question from this:
In my opinion, the label of enclosing subgraph assigned by the method called *Double-Radius Node Labeling* is nodes' **tag** which equivalent to the nodes type in data `mutag` or `proteins` mentioned in the [GNN](https://github.com/muhanzhang/DGCNN), not the **index** of nodes,  so how to determine the index of node in the enclosing subgraph and construct the another input `A`?

**Comment by XuSShuai** [comment]
Maybe my problem description is not clear.

![image](https://user-images.githubusercontent.com/29543183/49920490-4bf34480-fee5-11e8-8130-c7abd1790633.png)

What i want to know is how to build the adjacent matrix `A` of the subgraph? 
Looking for you reply.

**Comment by muhanzhang** [comment]
Hi. The vertex indices (vertex order) are not important as long as you ensure each row of A and each row of X correspond to the same vertex. In other words, the order can be arbitrary and does not matter to the GNN prediction.
