### ISSUE TITLE
which os are you working on?

### ISSUE THREAD

**Issue by cherrygeisha** [muhanzhang/SEAL#9]
I am testing your USair dataset. I found I encounter several error concerning cuda issues? Are you working on linux or windows system. I am currently working on mac system, maybe this is cause for this error?

**Comment by muhanzhang** [comment]
I am working on linux equipped with GPUs. Typically mac does not Nvidia GPUs for running cuda-based deep learning experiments. You may try setting _cmd_args.mode = 'cpu'_ within _Main.py_ to disable GPU training.
